"""Generate the site's LLM-study data module from the research CSVs.

`web/src/lib/llm-study.ts` used to be maintained by hand: 14 models x 8 parties x
2 conditions is 224 numbers transcribed from `research/out/profiles_*.csv`, which
is both tedious and a place for the site to drift silently away from the data it
claims to show. This script emits that file instead.

The instrument baseline is not stored anywhere: it is derived here as
``raw - dev``, which is exact for every row and needs no extra artifact.

Usage:
    python scripts/build_llm_study_ts.py
    python scripts/build_llm_study_ts.py --check   # fail if the file is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import pandas as pd

PARTIES = ["V", "MP", "S", "C", "L", "KD", "M", "SD"]
KEY_ORDER = ["C", "KD", "L", "M", "MP", "S", "SD", "V"]

OUT_DIR = Path("research/out")
SPEECH_CSV = OUT_DIR / "profiles_speech.csv"
NEUTRAL_CSV = OUT_DIR / "profiles_neutral.csv"
GEN_CACHE = OUT_DIR / "generations.jsonl"
TARGET = Path("web/src/lib/llm-study.ts")

DISPLAY_NAMES: dict[str, str] = {
    "anthropic/claude-opus-4.8": "Claude Opus 4.8",
    "anthropic/claude-sonnet-4.6": "Claude Sonnet 4.6",
    "deepseek/deepseek-v4-pro": "DeepSeek V4 Pro",
    "google/gemini-3.1-pro-preview": "Gemini 3.1 Pro",
    "google/gemini-3.5-flash": "Gemini 3.5 Flash",
    "google/gemma-4-31b-it": "Gemma 4 31B",
    "minimax/minimax-m3": "MiniMax M3",
    "moonshotai/kimi-k2.6": "Kimi K2.6",
    "nvidia/nemotron-3-ultra-550b-a55b": "Nemotron 3 Ultra",
    "openai/gpt-5.4": "GPT-5.4",
    "openai/gpt-5.5": "GPT-5.5",
    "qwen/qwen3.6-plus": "Qwen 3.6 Plus",
    "x-ai/grok-4.3": "Grok 4.3",
    "z-ai/glm-5.2": "GLM 5.2",
}


def _fmt(value: float) -> str:
    """Format a deviation the way the hand-written file did (two decimals)."""
    text = f"{value:.2f}"
    return "0" if text in {"0.00", "-0.00"} else text


def _reference(speech: pd.DataFrame) -> dict[str, float]:
    """Derive the instrument baseline as raw minus dev, averaged over models."""
    return {p: round(float((speech[f"raw_{p}"] - speech[f"dev_{p}"]).mean()), 2) for p in PARTIES}


def _profiles(df: pd.DataFrame, order: list[str], with_raw: bool) -> str:
    lines = []
    for model in order:
        row = df[df["model"] == model]
        if row.empty:
            continue
        r = row.iloc[0]
        dev = ", ".join(f"{p}: {_fmt(float(r[f'dev_{p}']))}" for p in KEY_ORDER)
        extra = ""
        if with_raw:
            extra = f", rawM: {float(r['raw_M']):.2f}, rawL: {float(r['raw_L']):.2f}"
        name = DISPLAY_NAMES.get(model, model)
        lines.append(f'  {{ name: "{name}", id: "{model}", dev: {{ {dev} }}{extra} }},')
    return "\n".join(lines)


def render(calibration_accuracy: float, calibration_n: int, run_date: str) -> str:
    """Build the full TypeScript module as a string."""
    speech = pd.read_csv(SPEECH_CSV).sort_values("dev_M", ascending=False)
    neutral = pd.read_csv(NEUTRAL_CSV)
    order = speech["model"].tolist()
    ref = _reference(speech)

    generations = sum(
        1 for line in GEN_CACHE.read_text(encoding="utf-8").splitlines() if line.strip()
    )
    rows = [
        json.loads(line)
        for line in GEN_CACHE.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    topics = len({r["topic"] for r in rows})
    providers = len({m.split("/")[0] for m in order})

    ref_line = ", ".join(f"{p}: {ref[p]}" for p in PARTIES)
    return f"""import type {{ PartyCode }} from "./parties";

/**
 * Results of the LLM writing-style study (research/llm_language_profile.py).
 * GENERATED by scripts/build_llm_study_ts.py. Do not edit by hand.
 * Classified with the DEPLOYED classifier (maktsprak_classifier_clean), the same
 * model the site serves.
 * {len(order)} models, {topics} topics, 2 conditions, 3 samples/cell, {generations} generations.
 *
 * dev = mean classifier probability minus the instrument baseline (the same model
 * averaged over a party-balanced sample of real speech). rawM/rawL are the
 * uncorrected mean shares (speech condition).
 */

export interface ModelProfile {{
  name: string;
  id: string;
  dev: Record<PartyCode, number>;
  rawM?: number;
  rawL?: number;
}}

/** Instrument baseline: mean output of the deployed model on balanced real speech. */
export const REFERENCE: Record<PartyCode, number> = {{
  {ref_line},
}};

/** Speech condition, sorted by deviation toward M. */
export const SPEECH: ModelProfile[] = [
{_profiles(speech, order, with_raw=True)}
];

/** Neutral control (civil-servant register), same model order as SPEECH. */
export const NEUTRAL: ModelProfile[] = [
{_profiles(neutral, order, with_raw=False)}
];

export const STUDY_META = {{
  models: {len(order)}, providers: {providers}, topics: {topics}, samplesPerCell: 3,
  generations: {generations}, calibrationAccuracy: {calibration_accuracy},
  calibrationN: {calibration_n}, runDate: "{run_date}",
}};
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--calibration-accuracy", type=float, default=0.475)
    parser.add_argument("--calibration-n", type=int, default=480)
    parser.add_argument("--run-date", default="2026-07-21")
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the target is stale instead of writing it",
    )
    args = parser.parse_args()

    rendered = render(args.calibration_accuracy, args.calibration_n, args.run_date)
    if args.check:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != rendered:
            print(f"STALE: {TARGET} does not match the research CSVs. Rerun without --check.")
            sys.exit(1)
        print(f"OK: {TARGET} matches the research CSVs.")
        return

    TARGET.write_text(rendered, encoding="utf-8")
    print(f"Wrote {TARGET}")


if __name__ == "__main__":
    main()
